package com.benandow.android.gui.layout.statistics;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;

public class Main {

	private static String[] stockViews = new String[]{
			"android.widget.AnalogClock",
			"android.widget.ImageView",
			"android.support.design.widget.FloatingActionButton",
			"android.widget.ImageButton",
			"android.widget.ZoomButton",
			"android.widget.QuickContactBadge",
			"android.widget.ZoomButton",
			"android.inputmethodservice.KeyboardView",
			"android.support.v7.app.MediaRouteButton",
			"android.widget.ProgressBar",
			"android.widget.AbsSeekBar",
			"android.widget.RatingBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.widget.SeekBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.support.v4.widget.ContentLoadingProgressBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.widget.RatingBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.widget.SeekBar",
			"android.support.v4.widget.Space",
			"android.support.v7.widget.Space",
			"android.view.SurfaceView",
			"android.opengl.GLSurfaceView",
			"android.widget.VideoView",
			"android.widget.TextView",
			"android.support.v7.widget.AppCompatTextView",
			"android.widget.Button",
			"android.support.v7.widget.AppCompatButton",
			"android.widget.CompoundButton",
			"android.widget.CheckBox",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.widget.RadioButton",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.widget.Switch",
			"android.support.v7.widget.SwitchCompat",
			"android.widget.ToggleButton",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.widget.CheckBox",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.widget.RadioButton",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.widget.Switch",
			"android.support.v7.widget.SwitchCompat",
			"android.widget.ToggleButton",
			"android.widget.CheckedTextView",
			"android.support.v7.widget.AppCompatCheckedTextView",
			"android.widget.Chronometer",
			"android.widget.DigitalClock",
			"android.widget.EditText",
			"android.support.v7.widget.AppCompatEditText",
			"android.widget.AutoCompleteTextView",
			"android.support.v7.widget.AppCompatAutoCompleteTextView",
			"android.widget.MultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.inputmethodservice.ExtractEditText",
			"android.support.v17.leanback.widget.SearchEditText",
			"android.support.v7.widget.AppCompatAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.widget.MultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.support.v17.leanback.widget.RowHeaderView",
			"android.widget.TextClock",
			"android.support.v7.widget.AppCompatAutoCompleteTextView",
			"android.support.v7.widget.AppCompatButton",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.support.v7.widget.AppCompatCheckedTextView",
			"android.support.v7.widget.AppCompatEditText",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.widget.AutoCompleteTextView",
			"android.support.v7.widget.AppCompatAutoCompleteTextView",
			"android.widget.MultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.widget.CheckBox",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.widget.CompoundButton",
			"android.widget.CheckBox",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.widget.RadioButton",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.widget.Switch",
			"android.support.v7.widget.SwitchCompat",
			"android.widget.ToggleButton",
			"android.support.v7.widget.AppCompatCheckBox",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.inputmethodservice.ExtractEditText",
			"android.widget.MultiAutoCompleteTextView",
			"android.support.v7.widget.AppCompatMultiAutoCompleteTextView",
			"android.widget.RadioButton",
			"android.support.v7.widget.AppCompatRadioButton",
			"android.support.v17.leanback.widget.SearchEditText",
			"android.widget.Switch",
			"android.support.v7.widget.SwitchCompat",
			"android.widget.ToggleButton",
			"android.view.TextureView",
			"android.view.ViewGroup",
			"android.widget.AbsoluteLayout",
			"android.webkit.WebView",
			"android.widget.AdapterView",
			"android.widget.AbsListView",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.ExpandableListView",
			"android.widget.AbsSpinner",
			"android.widget.Gallery",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.AdapterViewAnimator",
			"android.widget.AdapterViewFlipper",
			"android.widget.StackView",
			"android.widget.AdapterViewFlipper",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.ExpandableListView",
			"android.widget.Gallery",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.StackView",
			"android.widget.Adapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.widget.ListAdapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.WrapperListAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SpinnerAdapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v7.widget.ThemedSpinnerAdapter",
			"android.support.v7.widget.ThemedSpinnerAdapter",
			"android.widget.WrapperListAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.support.design.widget.CoordinatorLayout",
			"android.support.v4.widget.DrawerLayout",
			"android.app.FragmentBreadCrumbs",
			"android.widget.FrameLayout",
			"android.appwidget.AppWidgetHostView",
			"android.support.v17.leanback.widget.BaseCardView",
			"android.support.v17.leanback.widget.ImageCardView",
			"android.support.v17.leanback.widget.BrowseFrameLayout",
			"android.widget.CalendarView",
			"android.support.v7.widget.CardView",
			"android.support.design.widget.CollapsingToolbarLayout",
			"android.widget.DatePicker",
			"android.gesture.GestureOverlayView",
			"android.widget.HorizontalScrollView",
			"android.support.design.widget.TabLayout",
			"android.widget.MediaController",
			"android.support.design.widget.NavigationView",
			"android.support.v4.widget.NestedScrollView",
			"android.support.percent.PercentFrameLayout",
			"android.widget.ScrollView",
			"android.support.v17.leanback.widget.SearchOrbView",
			"android.support.v17.leanback.widget.SpeechOrbView",
			"android.widget.TabHost",
			"android.support.v13.app.FragmentTabHost",
			"android.widget.TimePicker",
			"android.support.v17.leanback.widget.TitleView",
			"android.widget.ViewAnimator",
			"android.widget.ViewFlipper",
			"android.widget.ViewSwitcher",
			"android.widget.ImageSwitcher",
			"android.widget.TextSwitcher",
			"android.widget.ImageSwitcher",
			"android.widget.TextSwitcher",
			"android.support.v13.app.FragmentTabHost",
			"android.support.v17.leanback.widget.ImageCardView",
			"android.widget.ImageSwitcher",
			"android.support.v17.leanback.widget.SpeechOrbView",
			"android.support.design.widget.TabLayout",
			"android.widget.TextSwitcher",
			"android.widget.ViewFlipper",
			"android.widget.ViewSwitcher",
			"android.widget.ImageSwitcher",
			"android.widget.TextSwitcher",
			"android.support.v7.widget.GridLayout",
			"android.widget.LinearLayout",
			"android.widget.ActionMenuView",
			"android.support.design.widget.AppBarLayout",
			"android.support.v17.leanback.widget.ListRowHoverCardView",
			"android.support.v17.leanback.widget.ListRowView",
			"android.widget.NumberPicker",
			"android.widget.RadioGroup",
			"android.widget.SearchView",
			"android.widget.TabWidget",
			"android.widget.TableLayout",
			"android.widget.TableRow",
			"android.support.design.widget.TextInputLayout",
			"android.widget.ZoomControls",
			"android.support.v7.widget.LinearLayoutCompat",
			"android.support.v7.widget.ActionMenuView",
			"android.support.v7.widget.SearchView",
			"android.support.v4.view.PagerTitleStrip",
			"android.support.v4.view.PagerTabStrip",
			"android.support.v7.widget.RecyclerView",
			"android.support.v17.leanback.widget.HorizontalGridView",
			"android.support.v17.leanback.widget.VerticalGridView",
			"android.widget.RelativeLayout",
			"android.widget.DialerFilter",
			"android.support.percent.PercentRelativeLayout",
			"android.support.v17.leanback.widget.SearchBar",
			"android.widget.TwoLineListItem",
			"android.support.v17.leanback.widget.ShadowOverlayContainer",
			"android.widget.SlidingDrawer",
			"android.support.v4.widget.SlidingPaneLayout",
			"android.support.v4.widget.SwipeRefreshLayout",
			"android.support.v7.widget.Toolbar",
			"android.media.tv.TvView",
			"android.support.v4.view.ViewPager",
			"android.widget.AbsListView",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.ExpandableListView",
			"android.widget.AbsSpinner",
			"android.widget.Gallery",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.support.v7.widget.ActionMenuView",
			"android.widget.AdapterViewAnimator",
			"android.widget.AdapterViewFlipper",
			"android.widget.StackView",
			"android.widget.AdapterViewFlipper",
			"android.support.design.widget.AppBarLayout",
			"android.support.v7.widget.AppCompatSpinner",
			"android.appwidget.AppWidgetHostView",
			"android.support.v17.leanback.widget.BaseCardView",
			"android.support.v17.leanback.widget.ImageCardView",
			"android.support.v17.leanback.widget.BrowseFrameLayout",
			"android.view.ViewStub",
			"android.widget.AbsListView",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.ExpandableListView",
			"android.widget.AbsSeekBar",
			"android.widget.RatingBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.widget.SeekBar",
			"android.support.v7.widget.AppCompatRatingBar",
			"android.widget.AbsSpinner",
			"android.widget.Gallery",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.AbsoluteLayout",
			"android.webkit.WebView",
			"android.support.v7.widget.ActionMenuView",
			"android.widget.AdapterView",
			"android.widget.AbsListView",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.ExpandableListView",
			"android.widget.AbsSpinner",
			"android.widget.Gallery",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.AdapterViewAnimator",
			"android.widget.AdapterViewFlipper",
			"android.widget.StackView",
			"android.widget.AdapterViewFlipper",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.ExpandableListView",
			"android.widget.Gallery",
			"android.widget.GridView",
			"android.widget.ListView",
			"android.widget.ExpandableListView",
			"android.widget.Spinner",
			"android.support.v7.widget.AppCompatSpinner",
			"android.widget.StackView",
			"android.widget.Adapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.widget.ListAdapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.WrapperListAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SpinnerAdapter",
			"android.widget.ArrayAdapter",
			"android.widget.BaseAdapter",
			"android.widget.ArrayAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.CursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v4.widget.ResourceCursorAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.widget.SimpleAdapter",
			"android.support.v4.widget.SimpleCursorAdapter",
			"android.support.v7.widget.ThemedSpinnerAdapter",
			"android.support.v7.widget.ThemedSpinnerAdapter",
			"android.widget.WrapperListAdapter",
			"android.widget.HeaderViewListAdapter",
			"android.widget.AdapterViewAnimator",
			"android.widget.AdapterViewFlipper",
			"android.widget.StackView",
			"android.widget.AdapterViewFlipper"};

	private static HashSet<String> viewSet = new HashSet<String>(Arrays.asList(stockViews));
	
	public static void main(String[] args){
		File rootSmaliDir = new File(args[0]);
		scanDirectory(rootSmaliDir);
	}
	
	public static void scanDirectory(File dir) {
		File[] files = dir.listFiles();
		for (File file : files) {
			if (file.isDirectory()) {
				scanDirectory(file);
			} else {
				scanFile(file);
			}
		}
	}

	public static void scanFile(File f){
    	if(f.exists()){
    		BufferedReader reader = null;
    		try {
				reader = new BufferedReader(new FileReader(f));
				 String text = null;
				 String classname = null;
				 String superclass = null;
				 while ((text = reader.readLine()) != null) {
				        if(text.startsWith(".class")){
				        	String[] cnameArr = text.split(" ");
				        	classname = cnameArr[cnameArr.length -1];
				        }else if(text.startsWith(".super")){
				        	String[] cnameArr = text.split(" ");
				        	String supername = cnameArr[cnameArr.length -1];
				        	//If extends View or other types
				        	superclass = supername.substring(1, supername.length()-1).replace('/', '.');
				        			
				        	if(viewSet.contains(superclass)){
				        		System.out.println(classname + " extends " + superclass);
				        	}
				       }
				 }
				reader.close();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
    		
    	}
	}
	
	
}
